allow testpilotcloud-client to be everywhere without prerelease.

diff --git a/jenkins/obs_integration/templates/client/v1_8_0/BRANDNAME-client.spec.in b/jenkins/obs_integration/templates/client/v1_8_0/BRANDNAME-client.spec.in
--- a/jenkins/obs_integration/templates/client/v1_8_0/BRANDNAME-client.spec.in
+++ b/jenkins/obs_integration/templates/client/v1_8_0/BRANDNAME-client.spec.in
@@ -379,10 +379,12 @@ install -m 755 %{SOURCE1} $RPM_BUILD_ROOT/usr/bin/[% APPLICATION_EXECUTABLE %]
 
 %check
 ## use exit 0 instead of exit 1 to turn this into warnings:
-if [ "%{prerelease}" == "" ]; then
- expr match '%{distribution}' '.*:community:\(testing\|nightly\)' && { echo "Error: Need a prerelease here, not %{version}"; exit 1; }
-else
- expr match '%{distribution}' '.*:community:desktop' && { echo "Error: Must not have a prerelease here, not %{version}"; exit 1; }
+if [ "%{name}" != "testpilotcloud-client" ]; then
+  if [ "%{prerelease}" == "" ]; then
+    expr match '%{distribution}' '.*:community:\(testing\|nightly\)' && { echo "Error: Need a prerelease here, not %{version}"; exit 1; }
+  else
+    expr match '%{distribution}' '.*:community:desktop' && { echo "Error: Must not have a prerelease here, not %{version}"; exit 1; }
+  fi
 fi
 
 %if 0%{?fedora_version}
